defaults:
  - model: forest
  - hydra/hydra_logging: default
  - hydra/job_logging: custom
  - general: general
 
fit_model: True
input_data_path: "data/raw/heart.csv"
serialize_model: True
output_model_path: "models/model.pkl"

splitting_strategy: "holdout"
splitting_params:
  val_size: 0.1
  random_state: 3

predict_raw_data_path: "data/raw/example_for_predict.csv"
predict_out_data_path: "data/output/example_predicts.csv"
