apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replicaset
  labels:
    app: online-inference-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
        - image: spintowin/heart-dis:v1
          name: heart-dis
          ports:
            - containerPort: 8000