apiVersion: v1
kind: Pod
metadata: 
  name: online-inference-pod-probes
  labels:
    app: online-inference-pod-probes
spec:
  containers: 
    - image: spintowin/heart-dis:v4
      name: heart-dis
      ports:
        - containerPort: 8000
      resources: 
        requests: 
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      readinessProbe:
        httpGet: 
          path: /healthcheck
          port: 8000
        initialDelaySeconds: 15
        periodSeconds: 3 
      livenessProbe:
        httpGet:
          path: /healthcheck
          port: 8000
        initialDelaySeconds: 3
        periodSeconds: 3
