apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference-blue-green
  labels:
    app: online-inference-blue-green
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: online-inference
  template:
    metadata:
      labels:
        app: online-inference
    spec:
      containers:
        - image: spintowin/heart-dis:v3
          name: heart-dis
          ports:
            - containerPort: 8000
